# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rpj/a/projs/urho3d_viewer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rpj/a/projs/urho3d_viewer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rpj/a/projs/urho3d_viewer/CMakeFiles /home/rpj/a/projs/urho3d_viewer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rpj/a/projs/urho3d_viewer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named u3dv

# Build rule for target.
u3dv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 u3dv
.PHONY : u3dv

# fast build rule for target.
u3dv/fast:
	$(MAKE) -f CMakeFiles/u3dv.dir/build.make CMakeFiles/u3dv.dir/build
.PHONY : u3dv/fast

AnimatedCharacter.o: AnimatedCharacter.cpp.o

.PHONY : AnimatedCharacter.o

# target to build an object file
AnimatedCharacter.cpp.o:
	$(MAKE) -f CMakeFiles/u3dv.dir/build.make CMakeFiles/u3dv.dir/AnimatedCharacter.cpp.o
.PHONY : AnimatedCharacter.cpp.o

AnimatedCharacter.i: AnimatedCharacter.cpp.i

.PHONY : AnimatedCharacter.i

# target to preprocess a source file
AnimatedCharacter.cpp.i:
	$(MAKE) -f CMakeFiles/u3dv.dir/build.make CMakeFiles/u3dv.dir/AnimatedCharacter.cpp.i
.PHONY : AnimatedCharacter.cpp.i

AnimatedCharacter.s: AnimatedCharacter.cpp.s

.PHONY : AnimatedCharacter.s

# target to generate assembly for a file
AnimatedCharacter.cpp.s:
	$(MAKE) -f CMakeFiles/u3dv.dir/build.make CMakeFiles/u3dv.dir/AnimatedCharacter.cpp.s
.PHONY : AnimatedCharacter.cpp.s

DynamicCharacter.o: DynamicCharacter.cpp.o

.PHONY : DynamicCharacter.o

# target to build an object file
DynamicCharacter.cpp.o:
	$(MAKE) -f CMakeFiles/u3dv.dir/build.make CMakeFiles/u3dv.dir/DynamicCharacter.cpp.o
.PHONY : DynamicCharacter.cpp.o

DynamicCharacter.i: DynamicCharacter.cpp.i

.PHONY : DynamicCharacter.i

# target to preprocess a source file
DynamicCharacter.cpp.i:
	$(MAKE) -f CMakeFiles/u3dv.dir/build.make CMakeFiles/u3dv.dir/DynamicCharacter.cpp.i
.PHONY : DynamicCharacter.cpp.i

DynamicCharacter.s: DynamicCharacter.cpp.s

.PHONY : DynamicCharacter.s

# target to generate assembly for a file
DynamicCharacter.cpp.s:
	$(MAKE) -f CMakeFiles/u3dv.dir/build.make CMakeFiles/u3dv.dir/DynamicCharacter.cpp.s
.PHONY : DynamicCharacter.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/u3dv.dir/build.make CMakeFiles/u3dv.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/u3dv.dir/build.make CMakeFiles/u3dv.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/u3dv.dir/build.make CMakeFiles/u3dv.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... u3dv"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AnimatedCharacter.o"
	@echo "... AnimatedCharacter.i"
	@echo "... AnimatedCharacter.s"
	@echo "... DynamicCharacter.o"
	@echo "... DynamicCharacter.i"
	@echo "... DynamicCharacter.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

